# Generated by Django 3.1 on 2020-09-06 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiftmakeapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(choices=[('M', 'M'), ('W', 'W')], max_length=50)),
                ('distance', models.IntegerField()),
                ('style', models.CharField(choices=[('Fr', 'Fr'), ('Ba', 'Ba'), ('Br', 'Br'), ('Fly', 'Fly'), ('IM', 'IM'), ('FR', 'FR'), ('MR', 'MR')], max_length=10)),
            ],
        ),
        migrations.AddConstraint(
            model_name='competitionmodel',
            constraint=models.UniqueConstraint(fields=('name', 'year'), name='unique_competition'),
        ),
    ]
