# Generated by Django 3.1 on 2020-09-21 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiftmakeapp', '0003_shiftmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftmodel',
            name='member_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
