# Generated by Django 3.1 on 2020-11-26 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shiftmakeapp', '0005_entrymodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shiftmodel',
            name='member_count',
        ),
        migrations.AlterField(
            model_name='entrymodel',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry', to='shiftmakeapp.shiftmodel'),
        ),
        migrations.AlterField(
            model_name='shiftmodel',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift', to='shiftmakeapp.competitionmodel'),
        ),
    ]
