# Generated by Django 3.1.3 on 2020-11-28 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kappashiftapp', '0002_auto_20200830_0926'),
        ('shiftmakeapp', '0006_auto_20201126_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftmodel',
            name='timekeep',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timekeep_shift', to='kappashiftapp.membermodel'),
        ),
        migrations.AddField(
            model_name='shiftmodel',
            name='video',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_shift', to='kappashiftapp.membermodel'),
        ),
    ]
