# Generated by Django 3.1.3 on 2020-12-15 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kappashiftapp', '0002_auto_20200830_0926'),
        ('shiftmakeapp', '0007_auto_20201128_0351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftmodel',
            name='timekeep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timekeep_shift', to='kappashiftapp.membermodel'),
        ),
        migrations.AlterField(
            model_name='shiftmodel',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_shift', to='kappashiftapp.membermodel'),
        ),
    ]
