# Generated by Django 3.1 on 2020-08-30 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kappashiftapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membermodel',
            name='member_type',
            field=models.CharField(choices=[('選手', 'Swimmer'), ('マネージャー', 'Manager')], max_length=10),
        ),
        migrations.AlterField(
            model_name='membermodel',
            name='sex',
            field=models.CharField(choices=[('男', 'M'), ('女', 'W')], max_length=50),
        ),
    ]
